# Generated by Django 2.2 on 2020-01-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goblin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Goblin', max_length=45)),
                ('max_hp', models.IntegerField(default=20)),
                ('hp', models.IntegerField(default=20)),
                ('damage_min', models.IntegerField(default=2)),
                ('damage_max', models.IntegerField(default=4)),
                ('exp', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Slime', max_length=45)),
                ('max_hp', models.IntegerField(default=15)),
                ('hp', models.IntegerField(default=15)),
                ('damage_min', models.IntegerField(default=1)),
                ('damage_max', models.IntegerField(default=2)),
                ('exp', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
