# Generated by Django 2.2 on 2020-01-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(max_length=45)),
                ('max_hp', models.IntegerField(default=20)),
                ('hp', models.IntegerField(default=20)),
                ('damage_min', models.IntegerField(default=2)),
                ('damage_max', models.IntegerField(default=4)),
                ('exp', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Goblin',
        ),
        migrations.DeleteModel(
            name='Slime',
        ),
    ]
