# Generated by Django 2.2 on 2020-01-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_auto_20200131_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='name',
            field=models.CharField(default='Goblin', max_length=45),
        ),
    ]
