# Generated by Django 2.2 on 2020-01-31 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('start_hp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('max_hp', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('level', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chosen_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='character.ClassType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('damage_min', models.IntegerField()),
                ('damage_max', models.IntegerField()),
                ('crit_chance', models.IntegerField()),
                ('hit_chance', models.IntegerField()),
                ('level_req', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('for_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='character.ClassType')),
            ],
        ),
    ]
